### ISSUE TITLE
Data is not retained after upgrading the home app (new contract)

### ISSUE THREAD

**Issue by stellarmagnet** [AutarkLabs/about#36]
![image](https://user-images.githubusercontent.com/2584493/61863229-7ff90400-aecf-11e9-8d8e-99bd9a32b05a.png)

**Comment by ottodevs** [comment]
This does not seem like an actual issue, I reviewed the contract changes history and we basically changed our registry from an array to a mapping, so there is not an straightforward way to keep previous storage alive, since the core structures for that storage had change.

Since I don't find any reason to keep the issue open, I close it for now, feel free to re-open it if for any reason we need to research more on this.
